# Generated by Django 5.1.2 on 2024-11-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_reservations', models.DateField(verbose_name='Start date')),
                ('end_reservations', models.DateField(verbose_name='End date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('canceled', models.BooleanField(default=False, verbose_name='Is canceled')),
                ('approved', models.BooleanField(default=False)),
                ('appartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
