# Generated by Django 5.1.2 on 2024-11-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='appartment',
            new_name='apartment',
        ),
    ]
