# Generated by Django 5.1.2 on 2024-11-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_appartment_reservation_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_reservations',
            field=models.DateField(unique=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_reservations',
            field=models.DateField(unique=True, verbose_name='Start date'),
        ),
    ]
